#!/usr/bin/env python3
"""
Daily Health Report Generator for OPS Agent
Automated system health monitoring and reporting
"""

import json
import subprocess
import sys
from pathlib import Path
from datetime import datetime

class DailyHealthReport:
    def __init__(self):
        self.bridge_script = "/Users/redinside/.openclaw/scripts/agent_bridge.py"
        
    def get_system_health(self) -> dict:
        """Get complete system health status"""
        health = {
            "timestamp": datetime.now().isoformat(),
            "openclaw": self._get_openclaw_info(),
            "disk": self._get_disk_info(),
            "services": self._get_service_status(),
            "memory": self._get_memory_info()
        }
        return health
    
    def _get_openclaw_info(self) -> dict:
        """Get OpenClaw version and status"""
        try:
            result = subprocess.run([
                "python3", self.bridge_script, "version"
            ], capture_output=True, text=True, timeout=10)
            
            version = result.stdout.strip() if result.returncode == 0 else "Unknown"
            
            # Get status
            status_result = subprocess.run([
                "python3", self.bridge_script, "status"
            ], capture_output=True, text=True, timeout=10)
            
            if status_result.returncode == 0:
                status = json.loads(status_result.stdout)
            else:
                status = {"error": "Status check failed"}
            
            return {
                "version": version,
                "status": status
            }
        except Exception as e:
            return {"error": str(e)}
    
    def _get_disk_info(self) -> dict:
        """Get disk space information"""
        try:
            result = subprocess.run([
                "python3", self.bridge_script, "disk"
            ], capture_output=True, text=True, timeout=10)
            
            if result.returncode == 0:
                return json.loads(result.stdout)
            else:
                return {"error": "Disk check failed"}
        except Exception as e:
            return {"error": str(e)}
    
    def _get_service_status(self) -> dict:
        """Get service status"""
        try:
            result = subprocess.run([
                "python3", self.bridge_script, "status"
            ], capture_output=True, text=True, timeout=10)
            
            if result.returncode == 0:
                status = json.loads(result.stdout)
                return {
                    "gateway": status.get("gateway", {}),
                    "dashboard": status.get("dashboard", {}),
                    "node": status.get("node", {}),
                    "ollama": status.get("ollama", {})
                }
            else:
                return {"error": "Service check failed"}
        except Exception as e:
            return {"error": str(e)}
    
    def _get_memory_info(self) -> dict:
        """Get memory information"""
        try:
            result = subprocess.run([
                "python3", self.bridge_script, "sysinfo"
            ], capture_output=True, text=True, timeout=10)
            
            if result.returncode == 0:
                info = json.loads(result.stdout)
                return {
                    "model": info.get("model", "Unknown"),
                    "processor": info.get("processor", "Unknown"),
                    "memory": info.get("memory", "Unknown")
                }
            else:
                return {"error": "Memory check failed"}
        except Exception as e:
            return {"error": str(e)}
    
    def format_report(self, health: dict) -> str:
        """Format health report for Telegram"""
        report = f"""📊 DAILY SYSTEM HEALTH REPORT
📅 {datetime.now().strftime('%Y-%m-%d %H:%M')}

🔧 OPENCLAW
Version: {health['openclaw'].get('version', 'Unknown')}
Status: {self._format_service_status(health['openclaw'].get('status', {}))}

💾 DISK SPACE
Total: {health['disk'].get('total', 'Unknown')}
Used: {health['disk'].get('used', 'Unknown')}
Available: {health['disk'].get('available', 'Unknown')}
Usage: {health['disk'].get('usage_percent', 'Unknown')}

🖥️  SYSTEM
Model: {health['memory'].get('model', 'Unknown')}
Processor: {health['memory'].get('processor', 'Unknown')}
Memory: {health['memory'].get('memory', 'Unknown')}

🌐 SERVICES STATUS
Gateway: {self._format_service_status(health['services'].get('gateway', {}))}
Dashboard: {self._format_service_status(health['services'].get('dashboard', {}))}
Node: {self._format_service_status(health['services'].get('node', {}))}
Ollama: {self._format_service_status(health['services'].get('ollama', {}))}

📋 SUMMARY
Overall Status: {self._get_overall_status(health)}
Alerts: {self._get_alerts(health)}

---
Generated by OPS Agent via Agent Bridge"""
        return report
    
    def _format_service_status(self, service: dict) -> str:
        """Format service status"""
        if service.get("status") == "running":
            return "✅ Running"
        elif service.get("status") == "stopped":
            return "❌ Stopped"
        else:
            return f"⚠️ {service.get('status', 'Unknown')}"
    
    def _get_overall_status(self, health: dict) -> str:
        """Get overall system status"""
        services = health.get('services', {})
        running_services = 0
        total_services = 0
        
        for service_name, service in services.items():
            if isinstance(service, dict):
                total_services += 1
                if service.get('status') == 'running':
                    running_services += 1
        
        if total_services == 0:
            return "❓ Unknown status"
        elif running_services == total_services:
            return "✅ All systems operational"
        elif running_services >= total_services * 0.75:
            return "⚠️ Minor issues detected"
        else:
            return "❌ System issues detected"
    
    def _get_alerts(self, health: dict) -> str:
        """Get system alerts"""
        alerts = []
        
        # Disk space alert
        disk_usage = health.get('disk', {}).get('usage_percent', '0%')
        if disk_usage.endswith('%'):
            usage_num = int(disk_usage[:-1])
            if usage_num > 80:
                alerts.append("⚠️ High disk usage")
            elif usage_num > 90:
                alerts.append("❌ Critical disk usage")
        
        # Service alerts
        services = health.get('services', {})
        for name, service in services.items():
            if isinstance(service, dict):
                if service.get('status') != 'running':
                    alerts.append(f"❌ {name.title()} not running")
        
        return " | ".join(alerts) if alerts else "✅ No alerts"
    
    def send_telegram_report(self, report: str) -> bool:
        """Send report to Telegram"""
        try:
            # This would integrate with your Telegram system
            # For now, just print the report
            print("TELEGRAM REPORT:")
            print(report)
            return True
        except Exception as e:
            print(f"Failed to send Telegram report: {e}")
            return False

def main():
    """Generate and send daily health report"""
    reporter = DailyHealthReport()
    
    # Get system health
    health = reporter.get_system_health()
    
    # Format report
    report = reporter.format_report(health)
    
    # Send report
    reporter.send_telegram_report(report)
    
    # Save to log
    with open("/Users/redinside/.openclaw/logs/daily_health.log", "a") as f:
        f.write(f"\n{'='*50}\n{report}\n{'='*50}\n")

if __name__ == "__main__":
    main()
