#!/usr/bin/env python3
"""
Simple Disk Check Script for OPS Agent
Direct disk space monitoring without complex parsing
"""

import subprocess
import json
from datetime import datetime

def get_disk_info():
    """Get disk space information"""
    try:
        # Run df -h command directly
        result = subprocess.run(['df', '-h'], capture_output=True, text=True, timeout=10)
        
        if result.returncode == 0:
            lines = result.stdout.strip().split('\n')
            
            # Parse main volume (first real volume)
            for line in lines[1:]:
                if line.strip() and not line.startswith('map') and not line.startswith('Filesystem'):
                    parts = line.split()
                    if len(parts) >= 6:
                        return {
                            'filesystem': parts[0],
                            'size': parts[1],
                            'used': parts[2],
                            'available': parts[3],
                            'usage_percent': parts[4],
                            'mounted': parts[8] if len(parts) > 8 else parts[-1]
                        }
        return None
    except Exception as e:
        print(f"Error: {e}")
        return None

def get_largest_dirs():
    """Get largest directories"""
    try:
        result = subprocess.run([
            'du', '-sh', '/Users/redinside/*', '2>/dev/null', '|', 'sort', '-hr', '|', 'head', '10'
        ], capture_output=True, text=True, timeout=15)
        
        if result.returncode == 0:
            directories = []
            for line in result.stdout.strip().split('\n'):
                if line.strip():
                    parts = line.split('\t')
                    if len(parts) >= 2:
                        directories.append({
                            'size': parts[0],
                            'path': parts[1],
                            'name': parts[1].split('/')[-1]
                        })
            return directories
        return []
    except Exception as e:
        print(f"Error: {e}")
        return []

def format_report():
    """Format the disk report"""
    disk_info = get_disk_info()
    directories = get_largest_dirs()
    
    report = f"""💾 DISK SPACE MONITORING REPORT
📅 {datetime.now().strftime('%Y-%m-%d %H:%M')}

📊 MAIN VOLUME STATUS"""
    
    if disk_info:
        report += f"""
Size: {disk_info['size']}
Used: {disk_info['used']}
Available: {disk_info['available']}
Usage: {disk_info['usage_percent']}
Mount: {disk_info['mounted']}"""
    else:
        report += "\n❌ Could not get disk information"
    
    if directories:
        report += f"\n\n📁 LARGEST DIRECTORIES (Top {len(directories)}):"
        for i, directory in enumerate(directories[:10], 1):
            report += f"\n{i}: {directory['size']} - {directory['name']}"
    
    # Check for alerts
    if disk_info and disk_info['usage_percent'].endswith('%'):
        try:
            usage_num = int(disk_info['usage_percent'][:-1])
            if usage_num > 85:
                alert_level = "🔴 CRITICAL" if usage_num > 90 else "⚠️ WARNING"
                report += f"\n\n{alert_level} High disk usage: {disk_info['usage_percent']}"
            else:
                report += f"\n\n✅ Disk space healthy"
        except:
            report += f"\n\n✅ Disk space healthy"
    else:
        report += f"\n\n✅ Disk space healthy"
    
    report += "\n\n---\nGenerated by OPS Agent"
    return report

def main():
    """Generate and print disk report"""
    report = format_report()
    print(report)
    
    # Save to log
    with open("/Users/redinside/.openclaw/logs/disk_monitor.log", "a") as f:
        f.write(f"\n{'='*50}\n{report}\n{'='*50}\n")

if __name__ == "__main__":
    main()
